### ISSUE TITLE
Debug / Development cycle

### ISSUE THREAD

**Issue by tkaymak** [lotabout/CodeGenerator#7]
Whats the best development cycle? I find myself stuck in between writing the generator in vim, then copying into the settings dialogue of IntelliJ, then checking what has been generated after clicking apply. This way does not show any errors in the velocity code.

Is there a better way?

**Comment by lotabout** [comment]
@james-woods Personally I think there are two major obstacles:
1. There is no auto-completion for all the APIs. Thus it is hard to write the correct velocity code.
2. There is no live output. So that we need to execute it manually and check the result.

Unfortunately I do not know any good solutions. But for first problem, normally I will:
1. Open CodeGenerator project in Intellij.
2. Write the code in Intellij so that I can utilize all the autocompletion. For example find out all the possible functions of `StringUtils` or other stuff.

**Comment by lotabout** [comment]
Close due to inactivity. If you have other question or any better solution please reopen the issue.
